import 'dart:typed_data';

import '../transport/pi_transport.dart';
import 'central_access_models.dart';

final class WorkspaceAccessGrantRequest {
  WorkspaceAccessGrantRequest({
    required String clientKeyThumbprint,
    required this.protocolVersion,
  }) : clientKeyThumbprint = _validatedOpaqueValue(
         clientKeyThumbprint,
         'clientKeyThumbprint',
       );

  /// Identifies the connection key generated by this client.
  ///
  /// The request intentionally contains no user or Workspace selector. Friday
  /// Relay derives both from the authenticated personal Workspace session.
  final String clientKeyThumbprint;
  final PiProtocolVersion protocolVersion;

  @override
  String toString() =>
      'WorkspaceAccessGrantRequest(protocolVersion: $protocolVersion, '
      '<redacted>)';
}

/// Locally trusted values copied from the future versioned Friday Relay/Pi
/// Node contract. R0 intentionally defines no production defaults.
final class WorkspaceAccessGrantPolicy {
  WorkspaceAccessGrantPolicy({
    required this.maxTimeToLive,
    required String connectPath,
  }) : connectPath = _validatedConnectPath(connectPath) {
    if (maxTimeToLive <= Duration.zero) {
      throw ArgumentError('maxTimeToLive must be positive.');
    }
  }

  final Duration maxTimeToLive;
  final String connectPath;
}

final class WorkspaceAccessGrant {
  WorkspaceAccessGrant({
    required WorkspaceAccessGrantRequest request,
    required WorkspaceProjection workspace,
    required WorkspaceAccessGrantPolicy policy,
    required String grantId,
    required String nodeKeyThumbprint,
    required Uri connectUri,
    required DateTime issuedAt,
    required DateTime expiresAt,
    required Uint8List envelope,
  }) : grantId = _validatedOpaqueValue(grantId, 'grantId'),
       workspaceId = workspace.workspaceId,
       workspaceOrigin = workspace.origin,
       nodeKeyThumbprint = _validatedOpaqueValue(
         nodeKeyThumbprint,
         'nodeKeyThumbprint',
       ),
       clientKeyThumbprint = request.clientKeyThumbprint,
       protocolVersion = request.protocolVersion,
       connectUri = _validatedConnectUri(
         connectUri,
         workspace.origin,
         policy.connectPath,
       ),
       issuedAt = _validatedUtcInstant(issuedAt, 'issuedAt'),
       expiresAt = _validatedExpiry(issuedAt, expiresAt, policy.maxTimeToLive),
       _envelope = _validatedEnvelope(envelope);

  final String grantId;
  final String workspaceId;
  final String nodeKeyThumbprint;
  final String clientKeyThumbprint;
  final PiProtocolVersion protocolVersion;
  final Uri workspaceOrigin;
  final Uri connectUri;
  final DateTime issuedAt;
  final DateTime expiresAt;
  final Uint8List _envelope;

  Uint8List get envelope => Uint8List.fromList(_envelope);

  bool isExpiredAt(DateTime instant) {
    final checkedInstant = _validatedUtcInstant(instant, 'instant');
    return !checkedInstant.isBefore(expiresAt);
  }

  @override
  String toString() => 'WorkspaceAccessGrant(<redacted>)';
}

String _validatedOpaqueValue(String value, String name) {
  if (value.isEmpty ||
      value.length > 256 ||
      value.trim() != value ||
      value.codeUnits.any((unit) => unit <= 0x1f || unit == 0x7f)) {
    throw ArgumentError('Invalid $name.');
  }
  return value;
}

String _validatedConnectPath(String value) {
  if (!value.startsWith('/') ||
      value == '/' ||
      value.contains('?') ||
      value.contains('#') ||
      value.contains('\\') ||
      value.codeUnits.any((unit) => unit <= 0x1f || unit == 0x7f)) {
    throw ArgumentError('Invalid Workspace connect path.');
  }
  return value;
}

Uri _validatedConnectUri(Uri value, Uri origin, String connectPath) {
  final sameAuthority =
      value.host.toLowerCase() == origin.host.toLowerCase() && !value.hasPort;
  if (value.scheme != 'wss' ||
      !value.hasAuthority ||
      value.host.isEmpty ||
      value.userInfo.isNotEmpty ||
      !sameAuthority ||
      value.path != connectPath ||
      value.hasQuery ||
      value.hasFragment) {
    throw ArgumentError(
      'connectUri must match the trusted Workspace origin and connect policy.',
    );
  }
  return value;
}

DateTime _validatedUtcInstant(DateTime value, String name) {
  if (!value.isUtc) {
    throw ArgumentError('$name must be in UTC.');
  }
  return value;
}

DateTime _validatedExpiry(
  DateTime issuedAt,
  DateTime expiresAt,
  Duration maxTimeToLive,
) {
  _validatedUtcInstant(expiresAt, 'expiresAt');
  final timeToLive = expiresAt.difference(issuedAt);
  if (timeToLive <= Duration.zero || timeToLive > maxTimeToLive) {
    throw ArgumentError(
      'expiresAt must be after issuedAt and within the configured grant TTL.',
    );
  }
  return expiresAt;
}

Uint8List _validatedEnvelope(Uint8List value) {
  if (value.isEmpty) {
    throw ArgumentError('envelope must not be empty.');
  }
  return Uint8List.fromList(value);
}
